WIP : Minor updates to the readme.md
tabiya-tech/taxonomy-model-application pull request #102
Opened 2023-08-12 05:30 UTC by rav3n11

- Added a link to the testing guidelines to the readme
- Added a table of contents type section
- Rephrased a few things
- renamed the DEMO.md to Testing guidelines.md

2023-08-12 05:31 UTC, rav3n11 commented
Hey @ApostolosBenisis @Fidesnoella @jacob-js what do you think?

2023-08-14 14:56 UTC, rav3n11 commented
Hey @Fidesnoella and @jacob-js, the license file has been added... Ready for review and merge.

2023-08-14 15:03 UTC, jacob-js requested changes

2023-08-14 15:45 UTC, rav3n11 commented on README.md
> +- **[Backend](backend/)**: Explore the backend directory for detailed insights into the backend.
Yeah I actually like that... Fixing.

2023-08-15 15:42 UTC, jacob-js approved these changes

2023-08-16 08:13 UTC, merged