chore: improve ReadMe documentation
tabiya-tech/taxonomy-model-application pull request #124
Opened 2023-09-06 13:18 UTC by abayo-luc

## What does this PR do?
- [x] Add IaC detailed ReadMe file with relevant steps and links to get started. 
- [x] Add note in `/frontend/ReadMe.md` to inform the new the developer that we are using hash routes.

2023-09-07 07:34 UTC, rav3n11 commented on frontend/README.md
> +**NOTE**: This project uses `HashRouter` for routing. `HashRouter` uses the URL hash to simulate a full URL so that the page won't be reloaded when you navigate between routes. More on of how to defi
Love this. We needed this.

2023-09-07 11:17 UTC, rav3n11 commented on iac/ReadMe.md
> +aplumi up -y --stack dev
typo?

2023-09-11 14:55 UTC, jacob-js requested changes

2023-09-11 14:55 UTC, jacob-js commented on frontend/README.md
> +**NOTE**: This project uses `HashRouter` for routing. `HashRouter` uses the URL hash to simulate a full URL so that the page won't be reloaded when you navigate between routes. More on of how to defi
I don't think the hash router is used to prevent the reloading of pages when navigating between routes. This behavior is more of a default behavior of the react-router library.

2023-09-11 21:01 UTC, merged