feat: introducing app layout
tabiya-tech/taxonomy-model-application pull request #138
Opened 2023-09-18 12:24 UTC by abayo-luc

### What does this PR do?

- move taxonomy model app setup under /frontend/app direcotry
- reconfigure the routing to support layout context
- app directory folder stracture
- introduce app layout out provider to faciliate dynamic rendering of its components

### How can it be tested
You should be able to run the server `yarn start` and welcome page rendered, and be able to navigate to the following route:
- `/#/info`
- `/#/modeldirectory`

2023-09-19 08:49 UTC, jacob-js requested changes

2023-09-19 08:49 UTC, jacob-js commented on frontend/src/app/AppLayoutProvider/AppLayoutContext.tsx
>    contentHeader?: React.ReactNode;
Is there any reason for making this property optional while it's setter function is mandatory?

2023-09-19 08:49 UTC, jacob-js commented on frontend/src/app/components/AppLayout.tsx
> +        </Box>
I think `children` here doesn't give a clear picture of what content is supposed to be displayed here. E.g. AppHeader, ContentHeader, AppSidebar. It's clear in this case what it is to be rendered. I would suggest using a prop like `AppContent`

2023-09-19 08:50 UTC, rav3n11 commented on frontend/src/app/components/ContentHeaderContainer.tsx
> +import { useAppLayout } from '../AppLayoutProvider';
I can't seem to see where this is defined....

2023-09-19 08:53 UTC, rav3n11 commented on frontend/src/app/routerConfig.tsx
We deleted the config we had and started over?

2023-09-19 09:01 UTC, rav3n11 commented on frontend/src/app/AppLayoutProvider/AppLayoutProvider.tsx
Love this. :heart: What do you think about abstracting the getters and setters here instead of passing the actual state and stateSetter?

2023-09-20 14:10 UTC, rav3n11 commented on frontend/src/app/AppLayoutProvider.tsx
> +export const useAppLayout = () => {
Cool. :+1:

2023-09-20 14:10 UTC, rav3n11 commented on frontend/src/app/app.type.ts
I'm not sure we have separate type files so far...

2023-09-20 14:20 UTC, abayo-luc commented on frontend/src/app/components/AppLayout.tsx
> +        <Box
Yes those are being removed at @Fidesnoella and @jacob-js bring in those components.

2023-09-20 14:21 UTC, abayo-luc commented on frontend/src/app/app.type.ts
Let me fixed , I thought it was the pattern we are using. Should I keep them in their respective compartments?

2023-09-27 09:33 UTC, jacob-js requested changes

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/app/index.tsx
> +export default TaxonomyModelApp;
Why is this exported twice?

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/app/index.tsx
> +        <AppLayout data-testid={'TaxonomyModelApp'}>
Here the curly braces can be removed

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/app/router.test.tsx
>    it("should render the full application given root", async () => {
This description is not understandable. And also, in the whole project, we use `test()` instead of `it()`. Consider following this style for consistency.

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/app/router.test.tsx
>      renderWithRouter(routerPaths.ROOT);
I would recommend moving the declaration of the function `renderWithRouter()` in a separate file e.g. test_utilities. I'm sure it might be needed somewhere else, like in `Appsidebar.test.tsx`

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelDirectoryHeader/ModelDirectoryHeader.test.tsx
> +    render(<ModelDirectoryHeader {...defaultProps} />);
`// WHEN` section is missing here

2023-09-27 09:33 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelDirectoryHeader/ModelDirectoryHeader.test.tsx
> +    // GIVEN a ModelDirectoryHeader component
I'd recommend changing this comment for clarity this way: `GIVEN that the ModelDirectoryHeader component is rendered`. Someone might choose to make it even better than this.

2023-09-27 11:41 UTC, abayo-luc commented on frontend/src/app/router.test.tsx
>    it("should render the full application given root", async () => {
Nice catch but we should create a PR to refactor this implementation with the `it` statement since it being used in many place in the app.

2023-09-27 11:45 UTC, abayo-luc commented on frontend/src/modeldirectory/components/ModelDirectoryHeader/ModelDirectoryHeader.test.tsx
> +    render(<ModelDirectoryHeader {...defaultProps} />);
There's no specific "action" in this test, as I am only rendering and then checking,   so you might not need a WHEN section. Usually WHEN  is added for interaction,  like a button click or an input change.

2023-09-28 21:18 UTC, merged