Layout/app header
tabiya-tech/taxonomy-model-application pull request #139
Opened 2023-09-19 10:47 UTC by Fidesnoella

2023-09-19 11:33 UTC, rav3n11 commented on frontend/src/app/components/AppHeader.test.tsx
> +        const appHeaderIconsContainer = screen.getByTestId(DATA_TEST_ID.APP_HEADER_ICONS_CONTAINER);
Do we already need these icons in the appheader? They're non functional right?

2023-09-19 11:33 UTC, rav3n11 commented on frontend/src/app/components/AppHeader.test.tsx
> +    test.each([
Also consider having the app Icons row be a separate component, since there is definitely going to be some buisiness logic there, like showing and hiding context menus and manging the interactions... That stuff would be much easier to test if it were a separate component, no?

2023-09-19 11:33 UTC, rav3n11 commented on frontend/src/app/components/AppLayout.tsx
> -          style={{ backgroundColor: '#806e6e' }} // TODO: remove this
We'll finalize a way to use some styled components for these soon...

2023-09-19 13:35 UTC, abayo-luc requested changes

2023-09-19 13:35 UTC, abayo-luc commented on frontend/src/app/components/AppLayout.tsx
> +        <Box paddingX={2}
This is no longer necessary, we can just remove it.

2023-09-19 13:43 UTC, abayo-luc requested changes

2023-09-19 13:43 UTC, abayo-luc commented on frontend/src/app/components/AppHeader.tsx
> +            <img src='/logo.svg' alt="Tabiya" height={30} data-testid={DATA_TEST_ID.APP_HEADER_LOGO}/>
If I click on logo it should take me back to the root path `/`

2023-09-19 14:12 UTC, jacob-js commented on frontend/src/app/components/AppHeader.test.tsx
> +    test.each([
Alright, that sounds good, however, those icons since they're non-functional for now, we're not bothering with the business logic yet, so why not keep them there? Then we move them to a separate component once we need to add any logic to them. I think this can work for us for now.

2023-09-20 08:26 UTC, abayo-luc approved these changes

2023-09-20 10:02 UTC, merged