Layout/app sidebar
tabiya-tech/taxonomy-model-application pull request #140
Opened 2023-09-20 10:00 UTC by Fidesnoella

2023-09-20 10:09 UTC, abayo-luc requested changes
@Fidesnoella @jacob-js apply the feedback and bringing the unit test.

2023-09-20 10:09 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.tsx
> +                    <Box
At the end of the day they are gonna be links, can we add the link and appropriate route path.

2023-09-20 10:09 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.tsx
> +                        onClick={() => setIsActive(index)}
I like this, but you can use `react-router-dom` to know which route is active and render the background accordingly. 

This can be achieved by comparing the current path name from `useLocation` hook, with path attribute form iconData.

2023-09-20 10:09 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.tsx
> +const iconData = [
this is more than icon, it is gonna contain the icon, label, and path. I would suggest we re-name it to `items` or something more explicitly such as `appSidebarItems`

2023-09-21 10:18 UTC, abayo-luc requested changes

2023-09-21 10:18 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.test.tsx
> +      expect(computedBackgroundColor).toBe("rgb(92, 255, 159)");
since we are relying on the `active` class from NavLink , can we also assert it presence.

2023-09-21 10:18 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.test.tsx
> +      expect(linkElement).toHaveAttribute("href", `${iconLinkPathname}`);
Do we need the template literals here? can we just call `iconLinkPathname` variable.

2023-09-21 10:24 UTC, jacob-js commented on frontend/src/app/components/AppSidebar.tsx
> +export const TEXT = {
`TEXT` is the constant we use for the texts in the components that are used during testing. To understand this well you might want to check the ModelsTable component.

2023-09-21 10:52 UTC, abayo-luc commented on frontend/src/app/components/AppSidebar.tsx
> +export const TEXT = {
Then the variable name should be change to reflect what it is. `TEXT` as a variable name don't make sense.

2023-09-21 11:01 UTC, abayo-luc commented
@Fidesnoella @jacob-js you also have to resolve the merge conflict.

2023-09-22 08:49 UTC, merged