feat!: First dfraft for the themeing
tabiya-tech/taxonomy-model-application pull request #141
Opened 2023-09-20 10:16 UTC by rav3n11

- added font and colors in applicationTheme.ts 
- ->  added stories for app layout components [ probably conflics with noella and jacobs work ]

2023-09-20 13:02 UTC, abayo-luc requested changes

2023-09-20 14:14 UTC, rav3n11 commented on frontend/src/theme/applicationTheme.ts
>  const applicationTheme = createTheme({
Oh yeah... we are in the index.tsx line 19
```typescript
<ThemeProvider theme={applicationTheme}>
      <SnackbarProvider>
        <App />
      </SnackbarProvider>
    </ThemeProvider>
```

2023-09-20 14:31 UTC, rav3n11 commented
By the way @abayo-luc this pr is into your existing app-layout branch so... when we merge we'll only be merging one pr into main...

2023-09-21 07:36 UTC, abayo-luc requested changes

2023-09-21 07:36 UTC, abayo-luc commented on frontend/src/theme/applicationTheme.ts
> +      main: '#EEFF41',
don't we need to configure the primary, and accent colors  as well? 

I would suggest primary: #002147 while accent: #5CFF9F

2023-09-21 07:55 UTC, rav3n11 commented on frontend/src/theme/applicationTheme.ts
> +      main: '#EEFF41',
Yeah I was thinkng about taking colors one step at a time, but the primary color is cool... I'll add that. Accent on the other hand is a bit more tricky since it's not part of the materialUI palette spec, we might either have to discuss the colors we want to use and extend the spec, or use the existing color palette options in some way. I think we'll need to talk about it though...

2023-09-21 08:46 UTC, abayo-luc approved these changes

2023-09-21 10:14 UTC, merged