chore: add prettier in the dev process
tabiya-tech/taxonomy-model-application pull request #144
Opened 2023-09-22 10:02 UTC by jacob-js

2023-09-22 10:41 UTC, abayo-luc requested changes

2023-09-22 10:41 UTC, abayo-luc commented on frontend/.prettierignore
> +*.html
Why are we ignoring html, css, yml, json files?

2023-09-22 10:41 UTC, abayo-luc commented on frontend/package.json
>    "eslintConfig": {
I would move eslint configration in their own file like it is being done on the backend.

2023-09-22 19:41 UTC, ApostolosBenisis commented on frontend/package.json
>    "eslintConfig": {
@abayo-luc  in principle you are right, but i guess this generated so from the the create-react-app script so i suggest to leave for now.
However...... what is the reason for adding `prettier` hier in the first place.
After reading the documentation  [integrating-with-linters](https://prettier.io/docs/en/integrating-with-linters) and 
 [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), my conclusion is that we should not use the eslint plugin for prettier.

2023-09-22 19:48 UTC, ApostolosBenisis commented on frontend/package.json
> +    "format": "prettier --write ."
with what options is prettier run? yes, obviously the default, but do they make sense? 
i suggest to make them explicit and  use a .prettierrc.json or simiral file.
It would also make sense to use one share config for all the projects? Perhaps the same was we do the linking to the api-specifications we could create a link to @tabiya/prettier-config

2023-09-22 19:51 UTC, ApostolosBenisis commented on frontend/package.json
> +    "format": "prettier --write ."
ok agree the goal is to format automatically.
but we are a bit way from there. how about adding a `prettier --check .` ? and include that in the `run-before-merge.sh`

2023-09-22 19:51 UTC, ApostolosBenisis commented on run-before-merge.sh
> +  (cd api-specifications/ && yarn && yarn run lint && yarn run format && yarn run compile && yarn run test)
see comment [above](https://github.com/tabiya-tech/taxonomy-model-application/pull/144/files#r1334764754)

2023-09-22 19:57 UTC, ApostolosBenisis commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
i am not sure how this is actually working with the .prettierrc.json?
Do we really need this ? Perhaps there is additional steps required to setup intellij, so we must investigate ....

2023-09-22 19:57 UTC, ApostolosBenisis commented on api-specifications/.eslintrc
> +    "prettier"
added comment on the frontend

2023-09-27 07:49 UTC, abayo-luc requested changes

2023-09-27 07:49 UTC, abayo-luc commented on @tabiya/prettier-config/.prettierrc.json
> +}
can we configure the print width, I would suggest 80 or 100. 

Of cz if it is not already configured with some plugins or somewhere I am not aware of.

2023-10-06 17:05 UTC, closed without merging