feat: add and configure 404 page
tabiya-tech/taxonomy-model-application pull request #168
Opened 2023-10-06 11:31 UTC by abayo-luc

## What does this PR do?
- [x] Configure not found page 
- [x] Add 404 illustration (to be replaced in the future). 

<img width="1438" alt="Screenshot 2023-10-10 at 09 41 56" src="https://github.com/tabiya-tech/taxonomy-model-application/assets/20681465/5f2da934-16db-41f2-8f7c-81cb65c08b1d">

2023-10-06 16:55 UTC, ApostolosBenisis requested changes

2023-10-06 16:55 UTC, ApostolosBenisis commented on frontend/src/errorPage/NotFound.tsx
Add a simple render test
Add a story in story book ( stories are they way to test for accessibility issues)

2023-10-06 16:55 UTC, ApostolosBenisis commented on frontend/public/404.svg
where was this  sourced from and what is the license of this image?

2023-10-10 21:32 UTC, rav3n11 approved these changes

2023-10-10 21:32 UTC, rav3n11 commented on frontend/src/errorPage/NotFound.tsx
> +      <img src="/TabiyaLogo.svg" alt="not found" width="250px" data-testid={DATA_TEST_ID.NOT_FOUND_ILLUSTRATION} />
I thought we used rems instead of px?

2023-10-11 06:15 UTC, ApostolosBenisis commented on frontend/src/errorPage/NotFound.tsx
> +      <img src="/TabiyaLogo.svg" alt="not found" width="250px" data-testid={DATA_TEST_ID.NOT_FOUND_ILLUSTRATION} />
we use rem when we want something to have a size be relative to the font.
Here the logo's size is relative to the screen. Additionally this icon here is "special" as it is the main element in the content. Giving it a fixed size (and later adjusting that to be responsive) is fine.

2023-10-11 06:19 UTC, merged