feat(frontend): add ImportStatusPropertyField Component
tabiya-tech/taxonomy-model-application pull request #308
Opened 2024-03-07 06:46 UTC by irumvanselme

2024-03-07 16:32 UTC, jacob-js requested changes

2024-03-07 16:32 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +          <HelpTip>
A switch statement is needed here. The way we do with the ImportProcessStateIcon.

2024-03-07 16:32 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +      <Box display={"flex"} gap={theme.spacing(1)} alignItems={"center"} data-testid={DATA_TEST_ID.IMPORT_STATUS_FIELD}>
For the format, please do not enclose strings in curly-braces.

2024-03-07 16:32 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +      <Box display={"flex"} gap={theme.spacing(1)} alignItems={"center"} data-testid={DATA_TEST_ID.IMPORT_STATUS_FIELD}>
For the format, please do not enclose strings in curly braces.

2024-03-07 16:32 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.test.tsx
> +import { ModelInfoTypes } from "../../../../../../../../../../modelInfo/modelInfoTypes";
Use the absolute path for the import

2024-03-07 16:42 UTC, jacob-js requested changes

2024-03-07 16:42 UTC, jacob-js commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.test.tsx
> +
These tests can be made shorter by writing them in a parameterized way. Please refer to the tests for the importProcessStateIcon for example.

2024-03-07 17:09 UTC, rav3n11 reviewed
@irumvanselme I've added some changes based off of this branch and opened a pull request  [here](https://github.com/tabiya-tech/taxonomy-model-application/pull/311)... Check it out?

2024-03-08 09:03 UTC, irumvanselme commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.test.tsx
> +import { ModelInfoTypes } from "../../../../../../../../../../modelInfo/modelInfoTypes";
Fixing it

2024-03-08 09:03 UTC, irumvanselme commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +      <Box display={"flex"} gap={theme.spacing(1)} alignItems={"center"} data-testid={DATA_TEST_ID.IMPORT_STATUS_FIELD}>
Fixing it

2024-03-08 09:03 UTC, irumvanselme commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +      <Box display={"flex"} gap={theme.spacing(1)} alignItems={"center"} data-testid={DATA_TEST_ID.IMPORT_STATUS_FIELD}>
Fixing it

2024-03-08 09:04 UTC, irumvanselme commented on frontend/src/modeldirectory/components/ModelProperties/components/ModelPropertiesContent/components/ModelPropertiesImportExport/ImportTimeline/components/ImportStatusPropertyField/ImportStatusPropertyField.tsx
> +          <HelpTip>
Fixing it

2024-03-08 09:22 UTC, closed without merging