chore(backend-read-me): add running section on backend.
tabiya-tech/taxonomy-model-application pull request #313
Opened 2024-03-11 06:37 UTC by irumvanselme

2024-03-11 21:56 UTC, rav3n11 approved these changes
LGTM

2024-03-11 21:56 UTC, rav3n11 commented on backend/README.md
> +>It is specifically designed for deployment on [AWS Lambda](https://aws.amazon.com/lambda/), utilizing [plumni](https://www.pulumi.com) for its construction. It is composed of cloud functions, which
small typo on "through"

2024-03-11 21:56 UTC, rav3n11 commented on backend/README.md
> +>It is specifically designed for deployment on [AWS Lambda](https://aws.amazon.com/lambda/), utilizing [plumni](https://www.pulumi.com) for its construction. It is composed of cloud functions, which
small typo on "pulumi"

2024-03-11 21:56 UTC, rav3n11 commented on backend/README.md
> +>It is specifically designed for deployment on [AWS Lambda](https://aws.amazon.com/lambda/), utilizing [plumni](https://www.pulumi.com) for its construction. It is composed of cloud functions, which
If we are going to mention aws we should call the cloud functions by their native name on aws, Lambda functions...

2024-03-12 09:34 UTC, jacob-js requested changes

2024-03-12 09:34 UTC, jacob-js commented on backend/README.md
> +>It is specifically designed for deployment on [AWS Lambda](https://aws.amazon.com/lambda/), utilizing [pulumi](https://www.pulumi.com) for its construction. It is composed of aws, Lambda functions,
Another detail to pay attention to is that, in this README we don't explain specific concepts. Therefore, the part `This architecture choice emphasizes the backend's alignment with cloud-based environments, making it unsuitable for local development or API testing through the REST Client apps such as postman.` isn't important.

**Note:** We focus on the conciseness and clarity of the information we are providing in this file.

2024-03-12 09:34 UTC, jacob-js commented on backend/README.md
> +This backend is not designed for local development, you can't run it locally,
Let's make this:

`The backend project can't be run locally.`

2024-03-13 07:55 UTC, irumvanselme commented on backend/README.md
> +This backend is not designed for local development, you can't run it locally,
Fixed

2024-03-13 07:55 UTC, irumvanselme commented on backend/README.md
> +>It is specifically designed for deployment on [AWS Lambda](https://aws.amazon.com/lambda/), utilizing [pulumi](https://www.pulumi.com) for its construction. It is composed of aws, Lambda functions,
Fixed

2024-03-13 09:52 UTC, jacob-js approved these changes

2024-03-13 09:53 UTC, merged