Login UI
tabiya-tech/taxonomy-model-application pull request #333
Opened 2024-03-27 07:32 UTC by jacob-js

2024-03-27 13:33 UTC, irumvanselme requested changes

2024-03-27 13:33 UTC, irumvanselme commented on frontend/src/app/components/AppHeader.test.tsx
> +          <AppHeader />
Would you add this givenAppRouter into the test utilities and make it reusable so that whenever a team member wants to mock store they will be able to use this component

It can work like.

```js.
<MockedAuthProvider state ={{ user: {}, logout: mockLogoutFn }}>
 // {children}
</MockedAuthProvider>
```

2024-03-27 13:33 UTC, irumvanselme commented on frontend/src/app/components/AppHeader.tsx
> +        onClick={(event) => setAnchorEl(event.currentTarget)}
App Header is not 100% covered by tests.

<img width="521" alt="image" src="https://github.com/tabiya-tech/taxonomy-model-application/assets/61510549/d121d354-0487-4509-ba20-e4621a3eccbb">

<img width="1723" alt="image" src="https://github.com/tabiya-tech/taxonomy-model-application/assets/61510549/3d3e6ad3-a112-4b42-a56e-2549f7ac026d">

2024-04-03 09:48 UTC, irumvanselme approved these changes

2024-04-03 11:27 UTC, rav3n11 commented on frontend/src/app/components/AppHeader.test.tsx
> +import { act, fireEvent, waitFor, within } from "@testing-library/react";
Shouldn't we import these from _test_utilities?

2024-04-03 11:27 UTC, rav3n11 commented on frontend/src/app/components/AppHeader.tsx
> +  }, [authContext]);
Should this have the full auth-context as a dependency? Or just the auth-context.user?

2024-04-03 13:21 UTC, rav3n11 commented on frontend/src/app/components/AppHeader.tsx
> +  }, [authContext]);
I see why now... But we should still destructure and only use the dependencies that we need, the auth context could return anything and could change for any reason...

2024-04-04 00:00 UTC, merged