chore(envs): test environment
tabiya-tech/taxonomy-model-application pull request #387
Opened 2024-05-24 14:56 UTC by irumvanselme

2024-05-28 12:04 UTC, rav3n11 requested changes
Some minor changes.

2024-05-28 12:04 UTC, rav3n11 commented on iac/setup/src/index.ts
> +let theDomainName = domainName;
:laughing: I think we should call this variable somthing like resolvedDomainName...

2024-05-28 15:52 UTC, irumvanselme commented on .github/workflows/main.yml
>    setup-infrastructure:
Lets go for the first option, as syntax naming jobs in yml file doesn't support such names `[dev] .....` but now we are going to use `setup-infrastructure-dev`

2024-05-29 07:14 UTC, rav3n11 approved these changes

2024-05-29 08:53 UTC, merged