feat(calculating-interesting-measures): degreeCentrality calculations
tabiya-tech/taxonomy-model-application pull request #403
Opened 2024-06-20 13:13 UTC by irumvanselme

2024-06-20 19:54 UTC, rav3n11 requested changes
Some changes to consider

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.test.ts
> +});
Are we missing a test when the repositoryUpdateSkillDegreeCentrality throws? same with the occupationRepository.groupBySkillId?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.ts
> +
Shouldn't this be in a try/catch?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.ts
> +
cant any of these throw? Including tthe batchProcessor?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.ts
> +
No wait... the batch processor never throws... but the repository methods?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures.ts
> +import errorLogger from "../../common/errorLogger/errorLogger";
src/...

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.ts
> +
or is the idea that we let it bubble up to the measures.ts and catch it there?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.ts
> +
even so... perhaps we should log and rethrow... since we should test that it WILL throw if the repositories throw and not, maybe hang? (probably wont... but we should have a test, right?)

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/measures/degreeCentrallity.test.ts
> +import { BatchProcessor } from "../../batch/BatchProcessor";
src/...

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/index.ts
> +const importCompleted = async (modelId: string) => {
Dont we currently handle this in the parseFiles? If we're going to handle it here... shouldn't it be removed from there... since we're updating the state as completed twice? 
![image](https://github.com/tabiya-tech/taxonomy-model-application/assets/49443576/ec3e6229-5b2a-4ac4-ad65-5692eb98fac3)

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/index.ts
> +const importCompleted = async (modelId: string) => {
Didn't see that change here is why I mention it..

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/import/async/index.test.ts
> +    jest
should these maybe be in a beforeAll? Does that matter here?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/esco/skill/skillRepository.ts
> +      throw e;
shouldnt we be throwing err instead of e? So that whatever it bubbles up to also has all the context about the cause?

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/esco/skill/skillRepository.ts
> +import { ISkillConnection } from "../occupationToSkillRelation/occupationToSkillRelation.types";
src/...

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/esco/skill/skillRepository.test.ts
> +import { generateRandomNumber } from "../../_test_utilities/specialCharacters";
src/...

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/esco/occupationToSkillRelation/occupationToSkillRelationRepository.ts
> +   * Counts the number of OccupationToSkillRelation entries that have the given skillId.
we should maybe be more discriptive here, since it does do more besides counting...

2024-06-20 19:54 UTC, rav3n11 commented on backend/src/esco/occupationToSkillRelation/occupationToSkillRelationRepository.test.ts
> +      actualSkillConnectionsArray.sort((a, b) => a.skillId.localeCompare(b.skillId));
we can use some jest extended matchers here like toIncludeSameMembers() couldnt we? Instead of sorting?

2024-06-25 22:06 UTC, rav3n11 approved these changes
All files look good.. Lets deploy this with [pulumi up] and test the functionality, and we can merge

2024-06-26 09:53 UTC, Fidesnoella approved these changes

2024-06-26 12:01 UTC, merged